// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalPractice.API.Models;

public partial class GameRecord
{
    public int GameRecordId { get; set; }

    public int RoomId { get; set; }

    public string RoomName { get; set; }

    public int TotalRound { get; set; }

    public int RoundSeconds { get; set; }

    public DateTime CreateTime { get; set; }

    public virtual ICollection<GameRecordPlayer> GameRecordPlayers { get; set; } = new List<GameRecordPlayer>();

    public virtual Room Room { get; set; }
}