// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalPractice.API.Models;

public partial class GameRecordPlayer
{
    public int GameRecordPlayerId { get; set; }

    public int GameRecordId { get; set; }

    public int PlayerId { get; set; }

    public string PlayerName { get; set; }

    public int Score { get; set; }

    public int Rank { get; set; }

    public virtual GameRecord GameRecord { get; set; }
}