// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalPractice.API.Models;

public partial class GuessMessage
{
    public int MessageId { get; set; }

    public int RoomId { get; set; }

    public int PlayerId { get; set; }

    public string PlayerName { get; set; }

    public string Content { get; set; }

    public bool IsCorrect { get; set; }

    public DateTime CreateTime { get; set; }
}