// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalPractice.API.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public int RoomOwnerId { get; set; }

    public string RoomCode { get; set; }

    public string RoomName { get; set; }

    public RoomStatusEnum RoomStatus { get; set; }

    public int? CurrentDrawerId { get; set; }

    public int TotalRound { get; set; }

    public int? CurrentRound { get; set; }

    public string CurrentTopic { get; set; }

    public DateTime? RoundEndTime { get; set; }

    public int RoundSeconds { get; set; }

    public DateTime CreateTime { get; set; }

    public virtual ICollection<RoomPlayer> RoomPlayers { get; set; } = new List<RoomPlayer>();
}