// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalPractice.API.Models;

public partial class RoomPlayer
{
    public int RoomPlayersId { get; set; }

    public int RoomId { get; set; }

    public int PlayerId { get; set; }

    public string PlayerName { get; set; }

    public int Score { get; set; }

    public int DrawOrder { get; set; }

    public int IsOnline { get; set; }

    public int IsReady { get; set; }

    public DateTime JoinTime { get; set; }

    public virtual Room Room { get; set; }
}