// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SignalPractice.API.Models;

public partial class SignalPracticeContext : DbContext
{
    public SignalPracticeContext(DbContextOptions<SignalPracticeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<GuessMessage> GuessMessages { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<RoomPlayer> RoomPlayers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<WorkBank> WorkBanks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A0B248A904F");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(300);
        });

        modelBuilder.Entity<GuessMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__GuessMes__C87C0C9C7AF96B2A");

            entity.ToTable("GuessMessage");

            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.PlayerName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Log>(entity =>
        {
            entity.Property(e => e.Level).HasMaxLength(16);
            entity.Property(e => e.RemoteIp).HasMaxLength(50);
            entity.Property(e => e.TimeStamp).HasColumnType("datetime");
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.HasKey(e => e.RoomId).HasName("PK__Room__328639397C02695A");

            entity.ToTable("Room");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.CurrentTopic).HasMaxLength(300);
            entity.Property(e => e.RoomCode)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.RoomName)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.RoundEndTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<RoomPlayer>(entity =>
        {
            entity.HasKey(e => e.RoomPlayersId).HasName("PK__RoomPlay__5049A9684EDF07E7");

            entity.Property(e => e.IsOnline).HasDefaultValue(1);
            entity.Property(e => e.JoinTime).HasColumnType("datetime");
            entity.Property(e => e.PlayerName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Room).WithMany(p => p.RoomPlayers)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomPlayers_Room");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4C31D8C117");

            entity.ToTable("User");

            entity.Property(e => e.DeleteReason).HasMaxLength(500);
            entity.Property(e => e.IsDelete).HasAnnotation("Relational:DefaultConstraintName", "DF__User__IsDelete__4BAC3F29");
            entity.Property(e => e.RegistrationTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__User__Registrati__4AB81AF0");
            entity.Property(e => e.UserAccount)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserPassword)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserRole).HasMaxLength(50);
        });

        modelBuilder.Entity<WorkBank>(entity =>
        {
            entity.HasKey(e => e.WorkBankId).HasName("PK__WorkBank__D5E0AB8D9505A559");

            entity.ToTable("WorkBank");

            entity.Property(e => e.Word)
                .IsRequired()
                .HasMaxLength(300);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}