// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalPractice.API.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserAccount { get; set; }

    public string UserPassword { get; set; }

    public string UserName { get; set; }

    public DateOnly? UserBirthDate { get; set; }

    public GenderEnum UserGender { get; set; }

    public string UserHeadshot { get; set; }

    public string UserRole { get; set; }

    public RegisterMethodEnum UserRegisterMethod { get; set; }

    public DateTime RegistrationTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public int IsDelete { get; set; }

    public int? DeleteAdminId { get; set; }

    public string DeleteReason { get; set; }
}