// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalPractice.API.Models;

public partial class WorkBank
{
    public int WorkBankId { get; set; }

    public string Word { get; set; }

    public int CategoryId { get; set; }
}